default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sequencer_development

staging:
  <<: *default
  database: sequencer_staging

test:
  <<: *default
  database: sequencer_test

production:
  <<: *default
  database: sequencer_production
  password: <%= ENV['SEQUENCER_DATABASE_PASSWORD'] %>
